/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanExpiradoRouteImport } from './routes/plan-expirado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as ApiPublicTestWelcomeEmailRouteImport } from './routes/api.public.test-welcome-email'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api.public.hotmart-webhook'
import { Route as AuthenticatedAppSemanaRouteImport } from './routes/_authenticated.app.semana'
import { Route as AuthenticatedAppRecetasRouteImport } from './routes/_authenticated.app.recetas'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated.app.perfil'
import { Route as AuthenticatedAppFavoritosRouteImport } from './routes/_authenticated.app.favoritos'
import { Route as AuthenticatedAppComprasRouteImport } from './routes/_authenticated.app.compras'
import { Route as AuthenticatedAppRecetasSlugRouteImport } from './routes/_authenticated.app.recetas.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanExpiradoRoute = PlanExpiradoRouteImport.update({
  id: '/plan-expirado',
  path: '/plan-expirado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicTestWelcomeEmailRoute =
  ApiPublicTestWelcomeEmailRouteImport.update({
    id: '/api/public/test-welcome-email',
    path: '/api/public/test-welcome-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart-webhook',
  path: '/api/public/hotmart-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSemanaRoute = AuthenticatedAppSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRecetasRoute = AuthenticatedAppRecetasRouteImport.update({
  id: '/recetas',
  path: '/recetas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFavoritosRoute =
  AuthenticatedAppFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComprasRoute = AuthenticatedAppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRecetasSlugRoute =
  AuthenticatedAppRecetasSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAppRecetasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plan-expirado': typeof PlanExpiradoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/compras': typeof AuthenticatedAppComprasRoute
  '/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/recetas': typeof AuthenticatedAppRecetasRouteWithChildren
  '/app/semana': typeof AuthenticatedAppSemanaRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
  '/api/public/test-welcome-email': typeof ApiPublicTestWelcomeEmailRoute
  '/app/recetas/$slug': typeof AuthenticatedAppRecetasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plan-expirado': typeof PlanExpiradoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/compras': typeof AuthenticatedAppComprasRoute
  '/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/recetas': typeof AuthenticatedAppRecetasRouteWithChildren
  '/app/semana': typeof AuthenticatedAppSemanaRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
  '/api/public/test-welcome-email': typeof ApiPublicTestWelcomeEmailRoute
  '/app/recetas/$slug': typeof AuthenticatedAppRecetasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plan-expirado': typeof PlanExpiradoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/app/compras': typeof AuthenticatedAppComprasRoute
  '/_authenticated/app/favoritos': typeof AuthenticatedAppFavoritosRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/recetas': typeof AuthenticatedAppRecetasRouteWithChildren
  '/_authenticated/app/semana': typeof AuthenticatedAppSemanaRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
  '/api/public/test-welcome-email': typeof ApiPublicTestWelcomeEmailRoute
  '/_authenticated/app/recetas/$slug': typeof AuthenticatedAppRecetasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/plan-expirado'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/auth/callback'
    | '/app/compras'
    | '/app/favoritos'
    | '/app/perfil'
    | '/app/recetas'
    | '/app/semana'
    | '/api/public/hotmart-webhook'
    | '/api/public/test-welcome-email'
    | '/app/recetas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/plan-expirado'
    | '/reset-password'
    | '/app'
    | '/onboarding'
    | '/auth/callback'
    | '/app/compras'
    | '/app/favoritos'
    | '/app/perfil'
    | '/app/recetas'
    | '/app/semana'
    | '/api/public/hotmart-webhook'
    | '/api/public/test-welcome-email'
    | '/app/recetas/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/plan-expirado'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/auth/callback'
    | '/_authenticated/app/compras'
    | '/_authenticated/app/favoritos'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/recetas'
    | '/_authenticated/app/semana'
    | '/api/public/hotmart-webhook'
    | '/api/public/test-welcome-email'
    | '/_authenticated/app/recetas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PlanExpiradoRoute: typeof PlanExpiradoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
  ApiPublicTestWelcomeEmailRoute: typeof ApiPublicTestWelcomeEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-expirado': {
      id: '/plan-expirado'
      path: '/plan-expirado'
      fullPath: '/plan-expirado'
      preLoaderRoute: typeof PlanExpiradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/test-welcome-email': {
      id: '/api/public/test-welcome-email'
      path: '/api/public/test-welcome-email'
      fullPath: '/api/public/test-welcome-email'
      preLoaderRoute: typeof ApiPublicTestWelcomeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hotmart-webhook': {
      id: '/api/public/hotmart-webhook'
      path: '/api/public/hotmart-webhook'
      fullPath: '/api/public/hotmart-webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/semana': {
      id: '/_authenticated/app/semana'
      path: '/semana'
      fullPath: '/app/semana'
      preLoaderRoute: typeof AuthenticatedAppSemanaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/recetas': {
      id: '/_authenticated/app/recetas'
      path: '/recetas'
      fullPath: '/app/recetas'
      preLoaderRoute: typeof AuthenticatedAppRecetasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/favoritos': {
      id: '/_authenticated/app/favoritos'
      path: '/favoritos'
      fullPath: '/app/favoritos'
      preLoaderRoute: typeof AuthenticatedAppFavoritosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/compras': {
      id: '/_authenticated/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AuthenticatedAppComprasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/recetas/$slug': {
      id: '/_authenticated/app/recetas/$slug'
      path: '/$slug'
      fullPath: '/app/recetas/$slug'
      preLoaderRoute: typeof AuthenticatedAppRecetasSlugRouteImport
      parentRoute: typeof AuthenticatedAppRecetasRoute
    }
  }
}

interface AuthenticatedAppRecetasRouteChildren {
  AuthenticatedAppRecetasSlugRoute: typeof AuthenticatedAppRecetasSlugRoute
}

const AuthenticatedAppRecetasRouteChildren: AuthenticatedAppRecetasRouteChildren =
  {
    AuthenticatedAppRecetasSlugRoute: AuthenticatedAppRecetasSlugRoute,
  }

const AuthenticatedAppRecetasRouteWithChildren =
  AuthenticatedAppRecetasRoute._addFileChildren(
    AuthenticatedAppRecetasRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppComprasRoute: typeof AuthenticatedAppComprasRoute
  AuthenticatedAppFavoritosRoute: typeof AuthenticatedAppFavoritosRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppRecetasRoute: typeof AuthenticatedAppRecetasRouteWithChildren
  AuthenticatedAppSemanaRoute: typeof AuthenticatedAppSemanaRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppComprasRoute: AuthenticatedAppComprasRoute,
  AuthenticatedAppFavoritosRoute: AuthenticatedAppFavoritosRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppRecetasRoute: AuthenticatedAppRecetasRouteWithChildren,
  AuthenticatedAppSemanaRoute: AuthenticatedAppSemanaRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PlanExpiradoRoute: PlanExpiradoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
  ApiPublicTestWelcomeEmailRoute: ApiPublicTestWelcomeEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
