INSERT INTO public.recetas (
  slug, titulo, descripcion, tiempo_minutos, calorias, porciones,
  dificultad, categoria, badges, imagen_url,
  ingredientes, pasos, tip_nutricionista, info_nutricional,
  categoria_ingrediente_principal
) VALUES

('omelette-tres-quesos',
 'Omelette de tres quesos',
 'Cremoso, esponjoso y listo en 8 minutos. Una versión especial del clásico omelette para empezar el día con sabor.',
 8, 310, 1, 'facil', 'salado',
 ARRAY['alto en proteina','sin gluten','vegetariano'],
 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Huevos","cantidad":"2"},{"item":"Queso mozzarella rallado","cantidad":"20g"},{"item":"Queso crema light","cantidad":"1 cda"},{"item":"Queso parmesano rallado","cantidad":"1 cda"},{"item":"Cebollín","cantidad":"1 cda"},{"item":"Sal y pimienta","cantidad":"al gusto"}]'::jsonb,
 '["Bate los huevos con sal y pimienta hasta que espumen.","Calienta una sartén antiadherente con aceite en spray.","Vierte los huevos y cocina a fuego bajo sin revolver.","Cuando los bordes cuajen, agrega los tres quesos en el centro.","Dobla por la mitad, espera 1 minuto y sirve con cebollín."]'::jsonb,
 'Combinar tres tipos de queso aporta distintos perfiles proteicos. El queso crema suaviza la textura sin sumar muchas calorías.',
 '{"proteina":"24g","carbohidratos":"3g","grasas":"22g","fibra":"0g"}'::jsonb,
 'huevo'),

('tostadas-ricotta-salmon',
 'Tostadas de ricotta y salmón ahumado',
 'Elegante, proteico y listo en 5 minutos. Un desayuno que parece de restaurante pero se hace en casa.',
 5, 290, 1, 'facil', 'salado',
 ARRAY['alto en proteina','sin azucar','omega 3'],
 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pan integral tostado","cantidad":"2 rebanadas"},{"item":"Ricotta","cantidad":"3 cdas"},{"item":"Salmón ahumado","cantidad":"50g"},{"item":"Alcaparras","cantidad":"1 cdita"},{"item":"Eneldo fresco","cantidad":"al gusto"},{"item":"Limón","cantidad":"unas gotas"}]'::jsonb,
 '["Tuesta el pan a tu gusto.","Unta ricotta generosamente en cada tostada.","Coloca el salmón encima en láminas.","Decora con alcaparras, eneldo y unas gotas de limón."]'::jsonb,
 'El salmón aporta omega 3 que ayuda a reducir la inflamación y cuida la salud cardiovascular. Cómelo 2-3 veces por semana.',
 '{"proteina":"26g","carbohidratos":"24g","grasas":"11g","fibra":"3g"}'::jsonb,
 'salmon'),

('bowl-proteico-atun',
 'Bowl proteico de atún y aguacate',
 'Sin cocción, listo en 5 minutos. Rico en proteínas y grasas buenas para mantenerte satisfecha toda la mañana.',
 5, 330, 1, 'facil', 'salado',
 ARRAY['alto en proteina','sin gluten','sin azucar','keto'],
 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Atún en agua escurrido","cantidad":"1 lata (130g)"},{"item":"Aguacate maduro","cantidad":"1/2"},{"item":"Tomate cherry","cantidad":"6"},{"item":"Pepino","cantidad":"1/4"},{"item":"Jugo de limón","cantidad":"1 cda"},{"item":"Sal, pimienta y cilantro","cantidad":"al gusto"}]'::jsonb,
 '["Escurre bien el atún y colócalo en un bowl.","Corta el aguacate en cubitos, el tomate por la mitad y el pepino en rodajas.","Mezcla todo con jugo de limón, sal, pimienta y cilantro.","Sirve frío."]'::jsonb,
 'El atún en lata es una fuente de proteína magra accesible. Prioriza el enlatado en agua para reducir calorías de grasa innecesaria.',
 '{"proteina":"34g","carbohidratos":"8g","grasas":"16g","fibra":"5g"}'::jsonb,
 'atun'),

('huevos-al-horno-tomate',
 'Huevos al horno con tomate y hierbas',
 'Reconfortante y muy fácil. Los huevos se cocinan solos en el horno mientras tú te alistas.',
 20, 250, 1, 'facil', 'salado',
 ARRAY['alto en proteina','sin gluten','vegetariano','sin azucar'],
 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Huevos","cantidad":"2"},{"item":"Tomate perita","cantidad":"1"},{"item":"Aceite de oliva","cantidad":"1 cdita"},{"item":"Ajo","cantidad":"1 diente"},{"item":"Orégano y albahaca","cantidad":"al gusto"},{"item":"Sal y pimienta","cantidad":"al gusto"}]'::jsonb,
 '["Precalienta el horno a 190°C.","En un molde pequeño, coloca el tomate picado con ajo, aceite, orégano, sal y pimienta.","Hornea 8 minutos hasta que el tomate suelte jugo.","Rompe los huevos encima y hornea 8 minutos más hasta que las claras cuajen.","Sirve directo del molde con albahaca fresca."]'::jsonb,
 'Cocinar al horno sin grasa extra conserva los nutrientes del huevo. El tomate cocinado libera más licopeno que el crudo.',
 '{"proteina":"18g","carbohidratos":"6g","grasas":"14g","fibra":"2g"}'::jsonb,
 'huevo'),

('sandwich-proteico-pollo',
 'Sándwich proteico de pollo y mostaza',
 'El sándwich perfecto para llevar al trabajo. Rápido, saciante y sin ningún remordimiento.',
 10, 370, 1, 'facil', 'salado',
 ARRAY['alto en proteina','para llevar'],
 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pan integral","cantidad":"2 rebanadas"},{"item":"Pechuga de pollo cocida","cantidad":"100g"},{"item":"Mostaza Dijon","cantidad":"1 cda"},{"item":"Lechuga","cantidad":"2 hojas"},{"item":"Tomate","cantidad":"2 rodajas"},{"item":"Pepino","cantidad":"3 rodajas"}]'::jsonb,
 '["Unta la mostaza en ambas rebanadas de pan.","Coloca la lechuga, las rodajas de tomate y pepino.","Agrega el pollo en láminas o desmenuzado.","Cierra el sándwich y córtalo diagonalmente."]'::jsonb,
 'La mostaza Dijon casi no aporta calorías pero da mucho sabor. Es un sustituto inteligente de mayonesa o salsas procesadas.',
 '{"proteina":"36g","carbohidratos":"30g","grasas":"8g","fibra":"5g"}'::jsonb,
 'pollo'),

('tacos-claras-frijoles',
 'Tacos de claras y frijoles negros',
 'Un desayuno mexicano clásico en versión fit. Contundente, económico y lleno de proteína.',
 15, 350, 1, 'facil', 'salado',
 ARRAY['alto en proteina','sin gluten','vegetariano'],
 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Tortillas de maíz pequeñas","cantidad":"3"},{"item":"Claras de huevo","cantidad":"3"},{"item":"Frijoles negros cocidos","cantidad":"1/3 taza"},{"item":"Cebolla","cantidad":"1/4"},{"item":"Chile verde (opcional)","cantidad":"al gusto"},{"item":"Cilantro y sal","cantidad":"al gusto"}]'::jsonb,
 '["Saltea cebolla y chile en sartén con aceite en spray.","Agrega las claras y revuelve hasta cuajar.","Calienta los frijoles en microondas 1 minuto.","Calienta las tortillas en comal seco.","Arma los tacos con claras, frijoles y cilantro."]'::jsonb,
 'Los frijoles negros son ricos en fibra soluble que alimenta la microbiota intestinal. Comerlos en el desayuno estabiliza el azúcar todo el día.',
 '{"proteina":"28g","carbohidratos":"42g","grasas":"4g","fibra":"10g"}'::jsonb,
 'huevo'),

('tostada-hummus-verduras',
 'Tostada de hummus y verduras asadas',
 'Colorida, nutritiva y vegetariana. Lista en 10 minutos con lo que tienes en la nevera.',
 10, 280, 1, 'facil', 'salado',
 ARRAY['vegetariano','vegano','alto en fibra'],
 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pan integral","cantidad":"2 rebanadas"},{"item":"Hummus","cantidad":"3 cdas"},{"item":"Pimiento rojo asado","cantidad":"1/2"},{"item":"Calabacín","cantidad":"1/4"},{"item":"Tomate cherry","cantidad":"5"},{"item":"Aceite de oliva y orégano","cantidad":"al gusto"}]'::jsonb,
 '["Tuesta el pan.","Unta el hummus en cada tostada.","Corta las verduras y colócalas encima.","Rocía con aceite de oliva y orégano."]'::jsonb,
 'El hummus es una fuente excelente de proteína vegetal y hierro. Prepararlo en casa con garbanzo cocido lo hace aún más nutritivo.',
 '{"proteina":"11g","carbohidratos":"34g","grasas":"10g","fibra":"9g"}'::jsonb,
 'pan'),

('bowl-quinoa-huevo',
 'Bowl de quinoa con huevo poché y espinaca',
 'Un bowl completo con superalimentos. Proteína, hierro y carbohidratos complejos en un solo plato.',
 18, 380, 1, 'medio', 'salado',
 ARRAY['alto en proteina','sin gluten','vegetariano'],
 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Quinoa cocida","cantidad":"1/2 taza"},{"item":"Huevo","cantidad":"1"},{"item":"Espinaca fresca","cantidad":"1 taza"},{"item":"Aguacate","cantidad":"1/4"},{"item":"Jugo de limón","cantidad":"1 cdita"},{"item":"Sal, pimienta y aceite de oliva","cantidad":"al gusto"}]'::jsonb,
 '["Calienta la quinoa en microondas 1 minuto.","Saltea la espinaca con aceite y sal 2 minutos.","Pocha el huevo en agua con un chorrito de vinagre, 3 minutos.","Arma el bowl: quinoa, espinaca, aguacate en rodajas y huevo encima.","Rocía limón y pimienta."]'::jsonb,
 'La quinoa es uno de los pocos vegetales con proteína completa (todos los aminoácidos esenciales). Ideal para vegetarianas activas.',
 '{"proteina":"22g","carbohidratos":"34g","grasas":"16g","fibra":"7g"}'::jsonb,
 'huevo'),

('tortillas-espinaca-queso',
 'Tortillitas de espinaca y queso',
 'Mini tortillas verdes, crujientes por fuera y suaves por dentro. Perfectas para llevar.',
 15, 260, 2, 'facil', 'salado',
 ARRAY['vegetariano','alto en proteina','para llevar'],
 'https://images.unsplash.com/photo-1568625365131-079e026a927d?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Espinaca fresca","cantidad":"1 taza"},{"item":"Huevos","cantidad":"2"},{"item":"Harina de avena","cantidad":"2 cdas"},{"item":"Queso fresco desmenuzado","cantidad":"30g"},{"item":"Sal, ajo en polvo","cantidad":"al gusto"}]'::jsonb,
 '["Licúa la espinaca con los huevos hasta obtener mezcla verde.","Agrega la harina de avena, queso, sal y ajo.","Calienta una sartén y vierte pequeñas porciones.","Cocina 2 minutos por lado hasta dorar.","Sirve apiladas o fríalas lleva en tupper."]'::jsonb,
 'Agregar espinaca a la masa incrementa el hierro y el folato sin alterar el sabor. El queso fresco aporta calcio y proteína.',
 '{"proteina":"18g","carbohidratos":"14g","grasas":"13g","fibra":"3g"}'::jsonb,
 'huevo'),

('revuelto-salmon-papa',
 'Revuelto de salmón con papa y cebollín',
 'Un desayuno contundente y lleno de omega 3. Ideal para días de mucha actividad.',
 18, 400, 1, 'medio', 'salado',
 ARRAY['alto en proteina','sin gluten','omega 3'],
 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Salmón ahumado","cantidad":"60g"},{"item":"Papa mediana cocida","cantidad":"1"},{"item":"Huevos","cantidad":"2"},{"item":"Cebollín","cantidad":"2 cdas"},{"item":"Aceite de oliva","cantidad":"1 cdita"},{"item":"Sal y pimienta","cantidad":"al gusto"}]'::jsonb,
 '["Pica la papa cocida en cubitos y dórala en sartén con aceite.","Bate los huevos, agrega sal y pimienta.","Vierte los huevos sobre la papa y revuelve suavemente.","Cuando estén casi listos, agrega el salmón en trozos.","Sirve con cebollín picado encima."]'::jsonb,
 'La papa cocida en lugar de frita conserva el potasio y reduce las calorías a menos de la mitad. Combinarla con salmón es ideal post-ejercicio.',
 '{"proteina":"30g","carbohidratos":"28g","grasas":"16g","fibra":"3g"}'::jsonb,
 'salmon'),

('bowl-lentejas-verduras',
 'Bowl de lentejas con verduras salteadas',
 'Un desayuno LATAM inusual pero delicioso. Las lentejas dan energía sostenida todo el día.',
 15, 360, 1, 'facil', 'salado',
 ARRAY['vegano','sin gluten','alto en fibra','vegetariano'],
 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Lentejas cocidas","cantidad":"1/2 taza"},{"item":"Pimiento","cantidad":"1/2"},{"item":"Cebolla","cantidad":"1/4"},{"item":"Tomate","cantidad":"1"},{"item":"Comino y cúrcuma","cantidad":"al gusto"},{"item":"Aceite de oliva y sal","cantidad":"al gusto"}]'::jsonb,
 '["Saltea cebolla y pimiento en aceite de oliva 3 minutos.","Agrega el tomate picado, comino y cúrcuma. Cocina 3 minutos más.","Incorpora las lentejas cocidas y mezcla bien.","Calienta 2 minutos, ajusta sal y sirve."]'::jsonb,
 'Las lentejas tienen más proteína que la mayoría de los granos. La cúrcuma potencia su efecto antiinflamatorio natural.',
 '{"proteina":"18g","carbohidratos":"48g","grasas":"7g","fibra":"14g"}'::jsonb,
 'lentejas'),

('tostada-palta-tomate',
 'Tostada de palta con tomate y orégano',
 'La versión LATAM del avocado toast. Simple, sabrosa y lista en 5 minutos.',
 5, 270, 1, 'facil', 'salado',
 ARRAY['vegano','vegetariano','sin azucar'],
 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pan integral","cantidad":"2 rebanadas"},{"item":"Palta madura","cantidad":"1/2"},{"item":"Tomate","cantidad":"1"},{"item":"Orégano seco","cantidad":"al gusto"},{"item":"Aceite de oliva","cantidad":"1 cdita"},{"item":"Sal y ají molido","cantidad":"al gusto"}]'::jsonb,
 '["Tuesta el pan.","Aplasta la palta con un tenedor y sazona con sal.","Unta la palta en el pan.","Coloca rodajas de tomate encima.","Rocía con aceite, orégano y ají molido."]'::jsonb,
 'La palta es rica en ácido oleico, la misma grasa saludable del aceite de oliva. Ayuda a absorber vitaminas liposolubles del tomate como el licopeno.',
 '{"proteina":"7g","carbohidratos":"28g","grasas":"14g","fibra":"8g"}'::jsonb,
 'pan'),

('shakshuka-fit',
 'Shakshuka fit (huevos en salsa de tomate)',
 'El plato favorito del Mediterráneo y Medio Oriente. Colorido, especiado y muy saciante.',
 20, 310, 1, 'medio', 'salado',
 ARRAY['vegetariano','sin gluten','alto en proteina','antiinflamatorio'],
 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Huevos","cantidad":"2"},{"item":"Tomates perita","cantidad":"2"},{"item":"Pimiento rojo","cantidad":"1/2"},{"item":"Cebolla","cantidad":"1/4"},{"item":"Comino, páprika y cúrcuma","cantidad":"1 cdita c/u"},{"item":"Aceite de oliva y sal","cantidad":"al gusto"}]'::jsonb,
 '["Saltea cebolla y pimiento en aceite hasta suavizar.","Agrega tomate picado y especias. Cocina 8 minutos.","Haz dos hoyos en la salsa y rompe un huevo en cada uno.","Tapa y cocina 6 minutos a fuego bajo hasta que las claras cuajen.","Sirve directo de la sartén con pan integral."]'::jsonb,
 'La combinación de cúrcuma, comino y páprika convierte este plato en una bomba antiinflamatoria natural. Come la yema semilíquida para aprovechar la colina.',
 '{"proteina":"20g","carbohidratos":"18g","grasas":"16g","fibra":"5g"}'::jsonb,
 'huevo'),

('bowl-pollo-verduras',
 'Bowl de pollo desmenuzado con verduras',
 'Meal prep ideal. Cocina el pollo el domingo y arma tu bowl cada mañana en 5 minutos.',
 10, 390, 1, 'facil', 'salado',
 ARRAY['alto en proteina','sin gluten','sin azucar','meal prep'],
 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pechuga de pollo cocida","cantidad":"120g"},{"item":"Arroz integral cocido","cantidad":"1/3 taza"},{"item":"Brócoli al vapor","cantidad":"1/2 taza"},{"item":"Zanahoria rallada","cantidad":"1/4 taza"},{"item":"Salsa de soya baja en sodio","cantidad":"1 cdita"},{"item":"Ajonjolí","cantidad":"1 cdita"}]'::jsonb,
 '["Desmenuza el pollo cocido con dos tenedores.","Calienta el arroz y el brócoli en microondas 1 minuto.","Arma el bowl con todos los ingredientes.","Agrega la salsa de soya y espolvorea ajonjolí."]'::jsonb,
 'El pollo desmenuzado con arroz integral es la combinación ideal de proteína completa + carbohidrato complejo. Perfecto para días de entrenamiento.',
 '{"proteina":"42g","carbohidratos":"30g","grasas":"8g","fibra":"5g"}'::jsonb,
 'pollo'),

('empanada-integral-espinaca',
 'Empanadas integrales de espinaca y ricotta',
 'Mini empanadas saludables que puedes preparar el fin de semana y calentar cada mañana.',
 35, 280, 3, 'medio', 'salado',
 ARRAY['vegetariano','meal prep','horneado'],
 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Harina integral","cantidad":"1 taza"},{"item":"Aceite de oliva","cantidad":"2 cdas"},{"item":"Agua fría","cantidad":"1/3 taza"},{"item":"Espinaca cocida y escurrida","cantidad":"1 taza"},{"item":"Ricotta","cantidad":"1/2 taza"},{"item":"Ajo, sal, nuez moscada","cantidad":"al gusto"}]'::jsonb,
 '["Mezcla harina, aceite y agua hasta formar masa. Reposa 15 min.","Mezcla espinaca escurrida con ricotta, ajo y nuez moscada.","Estira la masa y corta círculos.","Rellena, cierra con tenedor y pinta con leche vegetal.","Hornea a 180°C durante 20 minutos."]'::jsonb,
 'Usar harina integral triplica la fibra respecto a la harina blanca. La ricotta aporta proteína sin tanta grasa como otros quesos.',
 '{"proteina":"12g","carbohidratos":"34g","grasas":"10g","fibra":"6g"}'::jsonb,
 'pan'),

('tostada-aguacate-sardina',
 'Tostada de aguacate y sardina',
 'Rica en omega 3 y muy económica. La combinación perfecta de grasas buenas en una tostada.',
 7, 300, 1, 'facil', 'salado',
 ARRAY['alto en proteina','omega 3','sin azucar'],
 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pan integral tostado","cantidad":"2 rebanadas"},{"item":"Aguacate maduro","cantidad":"1/2"},{"item":"Sardinas en agua escurridas","cantidad":"1 lata pequeña"},{"item":"Jugo de limón","cantidad":"1 cda"},{"item":"Perejil fresco","cantidad":"al gusto"},{"item":"Ají molido y sal","cantidad":"al gusto"}]'::jsonb,
 '["Tuesta el pan.","Aplasta el aguacate con limón y sal.","Unta en el pan.","Coloca las sardinas encima.","Decora con perejil y ají molido."]'::jsonb,
 'Las sardinas son una de las fuentes más económicas de omega 3 y vitamina D. Comerlas regularmente protege el cerebro y reduce la inflamación.',
 '{"proteina":"22g","carbohidratos":"24g","grasas":"14g","fibra":"6g"}'::jsonb,
 'salmon'),

('bowl-acai-proteico',
 'Bowl de açaí proteico con granola',
 'El bowl más instagrameable, ahora con extra de proteína. Frío, cremoso y lleno de antioxidantes.',
 8, 320, 1, 'facil', 'dulce',
 ARRAY['vegetariano','antioxidante','alto en proteina'],
 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pulpa de açaí congelada","cantidad":"100g"},{"item":"Banana congelada","cantidad":"1/2"},{"item":"Yogur griego","cantidad":"1/2 taza"},{"item":"Granola sin azúcar","cantidad":"3 cdas"},{"item":"Fresas","cantidad":"4"},{"item":"Coco rallado","cantidad":"1 cda"}]'::jsonb,
 '["Procesa el açaí, banana y yogur hasta obtener una mezcla espesa.","Vierte en un bowl frío.","Decora con granola, fresas en rodajas y coco rallado.","Sirve de inmediato."]'::jsonb,
 'El açaí tiene un alto poder antioxidante (ORAC). El yogur griego suma proteína y probióticos para una microbiota saludable.',
 '{"proteina":"18g","carbohidratos":"40g","grasas":"9g","fibra":"8g"}'::jsonb,
 'fruta'),

('crepes-avena-fresas',
 'Crepes de avena con fresas y miel',
 'Finitos, dorados y deliciosos. Con fresas frescas son irresistibles y totalmente saludables.',
 15, 290, 2, 'facil', 'dulce',
 ARRAY['vegetariano','sin harina','sin azucar'],
 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Avena en hojuelas","cantidad":"1/2 taza"},{"item":"Huevos","cantidad":"2"},{"item":"Leche descremada","cantidad":"1/4 taza"},{"item":"Fresas","cantidad":"1 taza"},{"item":"Miel de abejas","cantidad":"1 cdita"},{"item":"Canela","cantidad":"una pizca"}]'::jsonb,
 '["Licúa avena, huevos y leche hasta obtener mezcla lisa.","Calienta sartén antiadherente con aceite en spray.","Vierte porciones pequeñas y cocina 1.5 min por lado.","Corta las fresas y mézclalas con miel.","Sirve las crepes con las fresas encima."]'::jsonb,
 'Usar avena molida como base de las crepes da doble beneficio: elimina la harina refinada y agrega fibra beta-glucano.',
 '{"proteina":"16g","carbohidratos":"38g","grasas":"7g","fibra":"5g"}'::jsonb,
 'avena'),

('budin-chia-chocolate',
 'Budín de chía con cacao y avellanas',
 'Todo el sabor del chocolate sin azúcar añadida. Lo preparas la noche anterior y listo.',
 5, 280, 1, 'facil', 'dulce',
 ARRAY['vegano','sin gluten','omega 3','sin azucar','meal prep'],
 'https://images.unsplash.com/photo-1542691457-cbe4df041eb2?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Semillas de chía","cantidad":"3 cdas"},{"item":"Leche de almendras","cantidad":"1 taza"},{"item":"Cacao puro en polvo","cantidad":"1 cda"},{"item":"Endulzante natural","cantidad":"al gusto"},{"item":"Avellanas picadas","cantidad":"1 cda"},{"item":"Banana en rodajas","cantidad":"1/4"}]'::jsonb,
 '["Mezcla la chía con leche, cacao y endulzante.","Refrigera mínimo 4 horas o toda la noche.","Al servir, decora con avellanas picadas y rodajas de banana."]'::jsonb,
 'El cacao puro (sin azúcar) es rico en flavonoides que mejoran la circulación y el estado de ánimo. Elige cacao 100% para máximo beneficio.',
 '{"proteina":"10g","carbohidratos":"28g","grasas":"14g","fibra":"12g"}'::jsonb,
 'yogur'),

('tostada-francesa-platano',
 'Tostada francesa de plátano sin azúcar',
 'El desayuno favorito de la infancia, ahora sin culpa. Dulce natural del plátano sin azúcar añadida.',
 12, 300, 2, 'facil', 'dulce',
 ARRAY['vegetariano','sin azucar','reconfortante'],
 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pan integral","cantidad":"2 rebanadas gruesas"},{"item":"Huevo","cantidad":"1"},{"item":"Leche descremada","cantidad":"1/4 taza"},{"item":"Plátano maduro","cantidad":"1/2"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Extracto de vainilla","cantidad":"1/4 cdita"}]'::jsonb,
 '["Aplasta el plátano y mezcla con huevo, leche, canela y vainilla.","Sumerge las rebanadas de pan en la mezcla 30 segundos por lado.","Cocina en sartén caliente con aceite en spray, 2 minutos por lado.","Sirve con fruta fresca o una cdita de miel."]'::jsonb,
 'El plátano maduro endulza naturalmente sin necesidad de azúcar. Cuanto más maduro (más manchas), más dulce y más fácil de digerir.',
 '{"proteina":"12g","carbohidratos":"44g","grasas":"5g","fibra":"4g"}'::jsonb,
 'avena'),

('galletas-avena-arandano',
 'Galletas de avena y arándanos (sin horno)',
 'Listas en 10 minutos sin encender el horno. Perfectas para llevar en la cartera.',
 10, 220, 4, 'facil', 'dulce',
 ARRAY['vegano','sin horno','meal prep','sin azucar'],
 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Avena en hojuelas","cantidad":"1 taza"},{"item":"Mantequilla de maní","cantidad":"3 cdas"},{"item":"Miel o jarabe de agave","cantidad":"2 cdas"},{"item":"Arándanos secos","cantidad":"2 cdas"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Sal","cantidad":"una pizca"}]'::jsonb,
 '["Mezcla todos los ingredientes hasta integrar bien.","Forma bolitas y aplástalas con la palma.","Refrigera 20 minutos hasta que endurezcan.","Guarda en recipiente hermético en la nevera hasta 5 días."]'::jsonb,
 'La mantequilla de maní aporta grasas buenas y proteína que hace que estas galletas sacien mucho más que las comerciales.',
 '{"proteina":"7g","carbohidratos":"28g","grasas":"9g","fibra":"4g"}'::jsonb,
 'avena'),

('parfait-durazno-granola',
 'Parfait de durazno y granola casera',
 'Capas de yogur cremoso, durazno fresco y granola crujiente. Se ve hermoso y sabe mejor.',
 8, 260, 1, 'facil', 'dulce',
 ARRAY['vegetariano','alto en proteina','sin azucar'],
 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Yogur griego natural","cantidad":"3/4 taza"},{"item":"Durazno fresco","cantidad":"1"},{"item":"Granola sin azúcar","cantidad":"3 cdas"},{"item":"Miel","cantidad":"1 cdita"},{"item":"Extracto de vainilla","cantidad":"unas gotas"},{"item":"Menta fresca","cantidad":"al gusto"}]'::jsonb,
 '["Mezcla el yogur con vainilla.","En un vaso o bowl, alterna capas de yogur, durazno picado y granola.","Repite las capas.","Termina con miel y menta fresca."]'::jsonb,
 'El durazno fresco aporta vitamina C y betacaroteno. En verano, congélalo y úsalo todo el año en smoothies o parfaits.',
 '{"proteina":"18g","carbohidratos":"32g","grasas":"5g","fibra":"4g"}'::jsonb,
 'yogur'),

('waffle-avena-proteico',
 'Waffle de avena y proteína',
 'Crujiente por fuera, suave por dentro. Sin azúcar y con mucha más proteína que el waffle clásico.',
 15, 310, 1, 'facil', 'dulce',
 ARRAY['vegetariano','sin azucar','alto en proteina'],
 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Avena en hojuelas","cantidad":"1/2 taza"},{"item":"Huevo","cantidad":"1"},{"item":"Claras de huevo","cantidad":"2"},{"item":"Leche descremada","cantidad":"1/4 taza"},{"item":"Polvo para hornear","cantidad":"1/2 cdita"},{"item":"Canela y vainilla","cantidad":"al gusto"}]'::jsonb,
 '["Licúa todos los ingredientes hasta obtener mezcla lisa.","Precalienta la wafflera y rocía con aceite en spray.","Vierte la mezcla y cocina según instrucciones de tu wafflera (3-4 min).","Sirve con fruta fresca y miel."]'::jsonb,
 'Al agregar claras de huevo a la masa, duplicas la proteína del waffle sin sumar calorías. Perfecto para días de entrenamiento matutino.',
 '{"proteina":"22g","carbohidratos":"32g","grasas":"6g","fibra":"4g"}'::jsonb,
 'avena'),

('cazuela-frutas-yogur',
 'Cazuela de frutas con yogur y semillas',
 'Refrescante y colorida. Lista en 5 minutos y cero cocción. Un desayuno de colores.',
 5, 230, 1, 'facil', 'dulce',
 ARRAY['vegetariano','vegano','sin gluten','sin azucar'],
 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Papaya en cubos","cantidad":"1/2 taza"},{"item":"Mango en cubos","cantidad":"1/2 taza"},{"item":"Kiwi en rodajas","cantidad":"1"},{"item":"Yogur natural","cantidad":"1/2 taza"},{"item":"Semillas de calabaza","cantidad":"1 cda"},{"item":"Jugo de naranja","cantidad":"2 cdas"}]'::jsonb,
 '["Corta todas las frutas en trozos similares.","Mezcla con el jugo de naranja.","Sirve en un bowl o vaso.","Agrega el yogur al lado o encima.","Espolvorea semillas de calabaza."]'::jsonb,
 'Las semillas de calabaza son ricas en zinc, esencial para el sistema inmune y la salud hormonal femenina. Agrégalas a cualquier desayuno.',
 '{"proteina":"9g","carbohidratos":"38g","grasas":"5g","fibra":"6g"}'::jsonb,
 'fruta'),

('bizcocho-zanahoria-microondas',
 'Bizcocho de zanahoria en taza (microondas)',
 'En 3 minutos tienes un bizcocho esponjoso sin azúcar. Perfecto para cuando el antojo ataca.',
 5, 240, 1, 'facil', 'dulce',
 ARRAY['vegetariano','sin azucar','rapido'],
 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Harina de avena","cantidad":"3 cdas"},{"item":"Zanahoria rallada","cantidad":"2 cdas"},{"item":"Huevo","cantidad":"1"},{"item":"Leche descremada","cantidad":"2 cdas"},{"item":"Canela y jengibre en polvo","cantidad":"1/4 cdita c/u"},{"item":"Polvo para hornear","cantidad":"1/4 cdita"},{"item":"Endulzante","cantidad":"al gusto"}]'::jsonb,
 '["Mezcla todos los ingredientes en una taza grande.","Asegúrate de integrar bien la zanahoria rallada.","Microondas a potencia alta 2-2.5 minutos.","Deja reposar 1 minuto antes de comer."]'::jsonb,
 'La zanahoria aporta betacaroteno que el cuerpo convierte en vitamina A, esencial para la piel y la vista. Un snack dulce con beneficios reales.',
 '{"proteina":"10g","carbohidratos":"28g","grasas":"6g","fibra":"4g"}'::jsonb,
 'avena'),

('batido-mango-curcuma',
 'Batido dorado de mango y cúrcuma',
 'Tropical, antiinflamatorio y delicioso. El Golden Latte del desayuno en versión fit.',
 5, 220, 1, 'facil', 'dulce',
 ARRAY['vegano','sin gluten','antiinflamatorio','sin azucar'],
 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Mango congelado","cantidad":"1 taza"},{"item":"Leche de coco light","cantidad":"3/4 taza"},{"item":"Cúrcuma en polvo","cantidad":"1/2 cdita"},{"item":"Jengibre fresco rallado","cantidad":"1/4 cdita"},{"item":"Pimienta negra","cantidad":"una pizca"},{"item":"Miel o dátil","cantidad":"al gusto"}]'::jsonb,
 '["Coloca todos los ingredientes en la licuadora.","Procesa hasta obtener mezcla cremosa y suave.","Sirve frío en un vaso alto.","Decora con una pizca de cúrcuma encima."]'::jsonb,
 'La pimienta negra activa la absorción de curcumina (principio activo de la cúrcuma) hasta 2000%. No te saltes este ingrediente.',
 '{"proteina":"3g","carbohidratos":"42g","grasas":"6g","fibra":"4g"}'::jsonb,
 'fruta'),

('pancakes-camote-canela',
 'Pancakes de camote y canela',
 'Esponjosos, dulces y con sabor reconfortante. El camote les da una textura increíble.',
 20, 300, 2, 'medio', 'dulce',
 ARRAY['vegetariano','sin harina','sin azucar'],
 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Camote cocido y aplastado","cantidad":"1/2 taza"},{"item":"Huevos","cantidad":"2"},{"item":"Harina de avena","cantidad":"3 cdas"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Polvo para hornear","cantidad":"1/2 cdita"},{"item":"Vainilla","cantidad":"1/4 cdita"}]'::jsonb,
 '["Mezcla el camote aplastado con los huevos hasta integrar.","Agrega avena, canela, polvo y vainilla. Mezcla bien.","Cocina porciones en sartén antiadherente 2 minutos por lado.","Sirve con miel de maple o frutas frescas."]'::jsonb,
 'El camote es rico en betacaroteno y tiene índice glucémico más bajo que la papa. Da energía sin picos de azúcar en sangre.',
 '{"proteina":"14g","carbohidratos":"42g","grasas":"7g","fibra":"6g"}'::jsonb,
 'avena'),

('porridge-quinoa-coco',
 'Porridge de quinoa con leche de coco',
 'Una alternativa proteica a la avena. Cremoso, tropical y sin gluten.',
 15, 340, 1, 'facil', 'dulce',
 ARRAY['vegano','sin gluten','alto en proteina'],
 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Quinoa","cantidad":"1/4 taza"},{"item":"Leche de coco light","cantidad":"3/4 taza"},{"item":"Banana","cantidad":"1/2"},{"item":"Coco rallado","cantidad":"1 cda"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Mango picado","cantidad":"1/4 taza"}]'::jsonb,
 '["Cocina la quinoa con la leche de coco y canela a fuego bajo 12 minutos.","Revuelve constantemente hasta que espese.","Sirve en bowl.","Decora con banana, mango y coco rallado."]'::jsonb,
 'La quinoa cocinada en leche vegetal absorbe los sabores y queda cremosa como avena. Con proteína completa, es ideal para vegetarianos y veganos.',
 '{"proteina":"12g","carbohidratos":"54g","grasas":"8g","fibra":"6g"}'::jsonb,
 'avena'),

('tarta-manzana-avena',
 'Tarta de manzana y avena en sartén',
 'Todo el sabor de la tarta de manzana pero sin horno, sin azúcar y lista en 15 minutos.',
 15, 310, 1, 'facil', 'dulce',
 ARRAY['vegetariano','sin azucar','reconfortante'],
 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Avena en hojuelas","cantidad":"1/2 taza"},{"item":"Manzana","cantidad":"1"},{"item":"Huevo","cantidad":"1"},{"item":"Leche descremada","cantidad":"3 cdas"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Nueces picadas","cantidad":"1 cda"},{"item":"Polvo para hornear","cantidad":"1/4 cdita"}]'::jsonb,
 '["Ralla o pica la manzana muy fina.","Mezcla con avena, huevo, leche, canela y polvo.","Vierte en sartén caliente con aceite en spray.","Cocina 5 minutos tapado a fuego bajo.","Voltea con cuidado y cocina 3 minutos más.","Sirve con nueces por encima."]'::jsonb,
 'La manzana con cáscara aporta pectina, una fibra soluble que reduce el colesterol y da saciedad prolongada. No la peles.',
 '{"proteina":"11g","carbohidratos":"44g","grasas":"9g","fibra":"7g"}'::jsonb,
 'avena'),

('agua-fresca-sandia',
 'Agua fresca de sandía y menta',
 'Hidratación natural y deliciosa. Perfecta para los desayunos de verano o días calurosos.',
 5, 60, 1, 'facil', 'bebida',
 ARRAY['vegano','sin gluten','sin azucar','detox'],
 'https://images.unsplash.com/photo-1622597467836-f3e6707e1191?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Sandía sin semillas","cantidad":"2 tazas"},{"item":"Agua fría","cantidad":"1/2 taza"},{"item":"Menta fresca","cantidad":"5 hojas"},{"item":"Jugo de limón","cantidad":"1 cda"},{"item":"Hielo","cantidad":"al gusto"}]'::jsonb,
 '["Licúa la sandía con el agua y menta.","Cuela si lo prefieres sin pulpa.","Agrega el jugo de limón.","Sirve con hielo y hojas de menta."]'::jsonb,
 'La sandía tiene 92% de agua, por lo que hidrata mejor que muchas bebidas. Es baja en calorías y rica en licopeno para la piel.',
 '{"proteina":"1g","carbohidratos":"14g","grasas":"0g","fibra":"1g"}'::jsonb,
 'fruta'),

('leche-dorada-curcuma',
 'Leche dorada de cúrcuma (Golden Milk)',
 'La bebida antiinflamatoria más famosa del mundo. Reconfortante, especiada y sin cafeína.',
 7, 110, 1, 'facil', 'bebida',
 ARRAY['vegano','sin gluten','antiinflamatorio','sin azucar'],
 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Leche de almendras o avena","cantidad":"1 taza"},{"item":"Cúrcuma en polvo","cantidad":"1 cdita"},{"item":"Canela","cantidad":"1/2 cdita"},{"item":"Jengibre en polvo","cantidad":"1/4 cdita"},{"item":"Pimienta negra","cantidad":"una pizca"},{"item":"Miel o dátil","cantidad":"al gusto"}]'::jsonb,
 '["Calienta la leche vegetal a fuego bajo.","Agrega cúrcuma, canela, jengibre y pimienta.","Bate con batidor de globo o licuadora de mano.","Endulza al gusto.","Sirve caliente con una pizca extra de canela."]'::jsonb,
 'Beber Golden Milk en la mañana activa el sistema inmune y reduce marcadores inflamatorios. La pimienta es clave para activar la cúrcuma.',
 '{"proteina":"2g","carbohidratos":"14g","grasas":"3g","fibra":"1g"}'::jsonb,
 'cafe'),

('matcha-latte-fit',
 'Matcha latte fit',
 'Energía limpia sin el crash del café. El matcha te activa suavemente y te mantiene enfocada horas.',
 5, 90, 1, 'facil', 'bebida',
 ARRAY['vegano','sin gluten','sin azucar','antioxidante'],
 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Matcha en polvo","cantidad":"1 cdita"},{"item":"Agua caliente (no hirviendo)","cantidad":"2 cdas"},{"item":"Leche de avena","cantidad":"1 taza"},{"item":"Endulzante natural","cantidad":"al gusto"}]'::jsonb,
 '["Disuelve el matcha en el agua caliente con batidor hasta que no queden grumos.","Calienta la leche de avena y espúmala si tienes espumador.","Vierte la leche sobre el matcha.","Endulza y decora con una pizca de matcha."]'::jsonb,
 'El matcha contiene L-teanina que combina con la cafeína para dar energía sostenida y calma mental simultáneas. Sin ansiedad ni crash.',
 '{"proteina":"3g","carbohidratos":"16g","grasas":"2g","fibra":"1g"}'::jsonb,
 'cafe'),

('smoothie-verde-manzana',
 'Smoothie verde de manzana y espinaca',
 'Verde, dulce y nada amargo. La manzana equilibra el sabor de la espinaca perfectamente.',
 5, 160, 1, 'facil', 'bebida',
 ARRAY['vegano','sin gluten','detox','antiinflamatorio'],
 'https://images.unsplash.com/photo-1622597467836-f3e6707e1191?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Manzana verde","cantidad":"1"},{"item":"Espinaca fresca","cantidad":"1 taza"},{"item":"Pepino","cantidad":"1/2"},{"item":"Jugo de limón","cantidad":"1 cda"},{"item":"Agua o agua de coco","cantidad":"1/2 taza"},{"item":"Jengibre fresco","cantidad":"1 rodaja"}]'::jsonb,
 '["Lava y trocea todos los ingredientes.","Licúa todo junto hasta obtener mezcla homogénea.","Prueba y ajusta con más limón o jengibre.","Sirve frío con hielo."]'::jsonb,
 'Los smoothies verdes son la forma más eficiente de consumir verduras en el desayuno. La manzana enmascara el amargo y añade fructosa natural de absorción lenta.',
 '{"proteina":"3g","carbohidratos":"34g","grasas":"1g","fibra":"6g"}'::jsonb,
 'fruta'),

('jugo-naranja-zanahoria',
 'Jugo de naranja, zanahoria y jengibre',
 'El shot de vitaminas que necesitas cada mañana. Brillante, ácido y muy energizante.',
 7, 130, 1, 'facil', 'bebida',
 ARRAY['vegano','sin gluten','antiinflamatorio','vitamina C'],
 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Naranjas","cantidad":"2"},{"item":"Zanahoria","cantidad":"1"},{"item":"Jengibre fresco","cantidad":"1 cm"},{"item":"Cúrcuma","cantidad":"una pizca"},{"item":"Hielo","cantidad":"al gusto"}]'::jsonb,
 '["Exprime las naranjas.","Pasa la zanahoria y el jengibre por el extractor o licúalos con un poco de agua y cuela.","Mezcla todo en un vaso.","Agrega la cúrcuma y revuelve.","Sirve con hielo."]'::jsonb,
 'Este jugo aporta vitamina C equivalente al doble de la dosis diaria recomendada. El betacaroteno de la zanahoria se absorbe mejor con un poco de grasa —acompáñalo con nueces.',
 '{"proteina":"2g","carbohidratos":"28g","grasas":"0g","fibra":"4g"}'::jsonb,
 'fruta'),

('kefir-batido-frutas',
 'Kéfir batido con frutas tropicales',
 'Probiótico y delicioso. El kéfir cuida tu intestino y las frutas le dan el toque tropical.',
 5, 200, 1, 'facil', 'bebida',
 ARRAY['vegetariano','sin gluten','probiotico','antiinflamatorio'],
 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Kéfir de leche","cantidad":"1 taza"},{"item":"Mango congelado","cantidad":"1/2 taza"},{"item":"Piña en trozos","cantidad":"1/4 taza"},{"item":"Cúrcuma en polvo","cantidad":"1/4 cdita"},{"item":"Miel","cantidad":"1 cdita"}]'::jsonb,
 '["Coloca todos los ingredientes en la licuadora.","Procesa hasta obtener mezcla cremosa.","Prueba y ajusta con miel.","Sirve frío de inmediato."]'::jsonb,
 'El kéfir tiene hasta 60 cepas de bacterias beneficiosas, muchas más que el yogur. Consumirlo regularmente mejora la digestión y refuerza la inmunidad.',
 '{"proteina":"8g","carbohidratos":"32g","grasas":"4g","fibra":"2g"}'::jsonb,
 'yogur'),

('agua-jamaica-jengibre',
 'Agua de jamaica con jengibre',
 'La bebida más popular de México en versión desintoxicante. Sin azúcar y llena de antioxidantes.',
 10, 20, 2, 'facil', 'bebida',
 ARRAY['vegano','sin gluten','detox','sin azucar','antiinflamatorio'],
 'https://images.unsplash.com/photo-1622597467836-f3e6707e1191?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Flor de jamaica seca","cantidad":"1/4 taza"},{"item":"Agua","cantidad":"4 tazas"},{"item":"Jengibre fresco","cantidad":"2 rodajas"},{"item":"Canela en raja","cantidad":"1 pequeña"},{"item":"Endulzante natural","cantidad":"al gusto"}]'::jsonb,
 '["Hierve 2 tazas de agua con la jamaica, jengibre y canela 5 minutos.","Retira del fuego y deja reposar 5 minutos.","Cuela y agrega las 2 tazas de agua fría restantes.","Endulza al gusto y sirve con hielo.","Guarda en la nevera hasta 5 días."]'::jsonb,
 'La flor de jamaica es rica en antocianinas, antioxidantes que cuidan el corazón y reducen la presión arterial. Perfecta sin azúcar para aprovechar todos sus beneficios.',
 '{"proteina":"0g","carbohidratos":"5g","grasas":"0g","fibra":"0g"}'::jsonb,
 'fruta'),

('energy-balls-datil',
 'Energy balls de dátil y cacao',
 'Sin cocción, sin azúcar añadida y listas en 10 minutos. Energía real en cada bolita.',
 10, 180, 3, 'facil', 'snack',
 ARRAY['vegano','sin gluten','sin azucar','meal prep'],
 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Dátiles sin hueso","cantidad":"10"},{"item":"Avena en hojuelas","cantidad":"1/2 taza"},{"item":"Cacao puro en polvo","cantidad":"2 cdas"},{"item":"Mantequilla de almendras","cantidad":"2 cdas"},{"item":"Coco rallado para cubrir","cantidad":"2 cdas"}]'::jsonb,
 '["Procesa los dátiles hasta obtener una pasta.","Agrega avena, cacao y mantequilla. Procesa hasta integrar.","Si la mezcla está muy pegajosa, refrigera 10 minutos.","Forma bolitas y pásalas por coco rallado.","Guarda en nevera hasta 2 semanas."]'::jsonb,
 'Los dátiles endulzan naturalmente con un índice glucémico moderado gracias a su fibra. Son además fuente de hierro y potasio.',
 '{"proteina":"5g","carbohidratos":"26g","grasas":"8g","fibra":"4g"}'::jsonb,
 'avena'),

('granola-casera-frutos-secos',
 'Granola casera con frutos secos y miel',
 'Crujiente, dulce y mucho más económica que la del supermercado. Haz una tanda para toda la semana.',
 30, 290, 4, 'facil', 'snack',
 ARRAY['vegano','sin gluten','meal prep'],
 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Avena en hojuelas","cantidad":"2 tazas"},{"item":"Almendras picadas","cantidad":"1/4 taza"},{"item":"Nueces picadas","cantidad":"1/4 taza"},{"item":"Miel","cantidad":"3 cdas"},{"item":"Aceite de coco","cantidad":"2 cdas"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Sal","cantidad":"una pizca"}]'::jsonb,
 '["Precalienta el horno a 160°C.","Mezcla avena, frutos secos, canela y sal.","Calienta miel y aceite de coco juntos, vierte sobre la mezcla.","Extiende en bandeja y hornea 20 minutos, revolviendo a la mitad.","Deja enfriar completamente antes de guardar."]'::jsonb,
 'La granola casera tiene hasta 60% menos azúcar que las versiones comerciales. Controlas cada ingrediente y ahorras dinero al mismo tiempo.',
 '{"proteina":"8g","carbohidratos":"38g","grasas":"13g","fibra":"5g"}'::jsonb,
 'avena'),

('tostadas-mantequilla-mani',
 'Tostadas con mantequilla de maní y banana',
 'Clásico americano en versión fit. La combinación de proteína, grasa y carbohidrato perfecta.',
 5, 310, 1, 'facil', 'snack',
 ARRAY['vegetariano','sin azucar','rapido'],
 'https://images.unsplash.com/photo-1541519227354-08fa5d50c820?auto=format&fit=crop&w=800&q=80',
 '[{"item":"Pan integral","cantidad":"2 rebanadas"},{"item":"Mantequilla de maní natural","cantidad":"2 cdas"},{"item":"Banana","cantidad":"1/2"},{"item":"Miel","cantidad":"1 cdita"},{"item":"Canela","cantidad":"al gusto"}]'::jsonb,
 '["Tuesta el pan a tu gusto.","Unta mantequilla de maní en cada tostada.","Coloca rodajas de banana encima.","Rocía miel y espolvorea canela."]'::jsonb,
 'La mantequilla de maní natural (sin azúcar ni aceites añadidos) aporta proteína y ácido oleico. Revisa que el primer ingrediente sea solo maní.',
 '{"proteina":"12g","carbohidratos":"40g","grasas":"14g","fibra":"5g"}'::jsonb,
 'pan')

ON CONFLICT (slug) DO NOTHING;