-- Seed completo de 20 recetas para Desayuno Fit (espanhol neutro LATAM)
-- Idempotente: usa ON CONFLICT (slug) DO NOTHING

INSERT INTO public.recetas (slug, titulo, descripcion, tiempo_minutos, calorias, porciones, dificultad, categoria, badges, imagen_url, ingredientes, pasos, tip_nutricionista, info_nutricional) VALUES

('tostada-aguacate-huevo', 'Tostada de aguacate y huevo pochado', 'Una tostada cremosa con aguacate fresco y huevo pochado. Lista en 10 minutos para empezar el día con energía.', 10, 320, 1, 'facil', 'salado', ARRAY['alto en proteina','sin azucar'], 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80', '[{"item":"Pan integral","cantidad":"2 rebanadas"},{"item":"Aguacate maduro","cantidad":"1/2"},{"item":"Huevo","cantidad":"1"},{"item":"Limón","cantidad":"1/2 cdita"},{"item":"Sal y pimienta","cantidad":"al gusto"}]'::jsonb, '["Tuesta el pan integral hasta dorar.","Machaca el aguacate con limón, sal y pimienta.","Calienta agua con un chorrito de vinagre, rompe el huevo en una taza y deslízalo en remolino. Cocina 3 minutos.","Unta el aguacate sobre el pan y coloca el huevo encima."]'::jsonb, 'El aguacate aporta grasas buenas que mantienen la saciedad por más tiempo. Combínalo con proteína para evitar antojos a media mañana.', '{"proteina":"18g","carbohidratos":"28g","grasas":"15g","fibra":"8g"}'::jsonb),

('panqueques-avena-banana', 'Panqueques de avena y banana', 'Panqueques esponjosos sin harina ni azúcar refinada. Perfectos para un desayuno dulce y saludable.', 15, 280, 2, 'facil', 'dulce', ARRAY['sin harina','vegetariano'], 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80', '[{"item":"Avena en hojuelas","cantidad":"1 taza"},{"item":"Banana madura","cantidad":"1"},{"item":"Huevos","cantidad":"2"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Polvo para hornear","cantidad":"1 cdita"}]'::jsonb, '["Licúa la avena hasta hacer harina.","Agrega banana, huevos, canela y polvo. Procesa hasta integrar.","Cocina porciones en sartén caliente con poco aceite, 2 minutos por lado.","Sirve con fruta fresca o yogur."]'::jsonb, 'La avena es rica en fibra beta-glucano, que ayuda a regular el colesterol y a sentirte llena por más tiempo.', '{"proteina":"14g","carbohidratos":"42g","grasas":"7g","fibra":"6g"}'::jsonb),

('smoothie-bowl-frutos-rojos', 'Smoothie bowl de frutos rojos', 'Un bowl frío y cremoso lleno de antioxidantes. Ideal para mañanas calurosas.', 8, 240, 1, 'facil', 'dulce', ARRAY['vegetariano','sin gluten','antioxidante'], 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=800&q=80', '[{"item":"Frutos rojos congelados","cantidad":"1 taza"},{"item":"Banana congelada","cantidad":"1/2"},{"item":"Yogur griego natural","cantidad":"1/2 taza"},{"item":"Granola sin azúcar","cantidad":"2 cdas"},{"item":"Semillas de chía","cantidad":"1 cdita"}]'::jsonb, '["Licúa los frutos rojos, banana y yogur hasta obtener una mezcla espesa.","Vierte en un bowl.","Decora con granola, chía y frutas frescas extras."]'::jsonb, 'Los frutos rojos tienen muy bajo índice glucémico y son ricos en polifenoles, ideales para cuidar la piel.', '{"proteina":"12g","carbohidratos":"38g","grasas":"4g","fibra":"7g"}'::jsonb),

('huevos-revueltos-espinaca', 'Huevos revueltos con espinaca y queso fresco', 'Cremosos, sabrosos y listos en 7 minutos. Una opción salada cargada de proteína.', 7, 290, 1, 'facil', 'salado', ARRAY['alto en proteina','keto','sin gluten'], 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80', '[{"item":"Huevos","cantidad":"2"},{"item":"Espinaca fresca","cantidad":"1 taza"},{"item":"Queso fresco","cantidad":"30g"},{"item":"Aceite de oliva","cantidad":"1 cdita"},{"item":"Sal y pimienta","cantidad":"al gusto"}]'::jsonb, '["Bate los huevos con sal y pimienta.","Calienta el aceite y saltea la espinaca 1 minuto.","Agrega los huevos y revuelve a fuego bajo.","Cuando estén casi listos, añade el queso fresco desmenuzado."]'::jsonb, 'La espinaca aporta hierro y folato. Combinarla con huevo mejora la absorción de nutrientes.', '{"proteina":"22g","carbohidratos":"4g","grasas":"20g","fibra":"2g"}'::jsonb),

('overnight-oats-mango', 'Overnight oats de mango y coco', 'Lo dejas listo la noche anterior y desayunas en segundos al despertar. Tropical y refrescante.', 5, 310, 1, 'facil', 'dulce', ARRAY['vegano','sin gluten','meal prep'], 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80', '[{"item":"Avena en hojuelas","cantidad":"1/2 taza"},{"item":"Leche de coco","cantidad":"1/2 taza"},{"item":"Mango maduro","cantidad":"1/2"},{"item":"Coco rallado","cantidad":"1 cda"},{"item":"Semillas de chía","cantidad":"1 cda"}]'::jsonb, '["Mezcla la avena, leche de coco y chía en un frasco.","Refrigera durante toda la noche.","En la mañana, agrega mango picado y coco rallado por encima."]'::jsonb, 'El meal prep nocturno es tu mejor aliado en semanas ocupadas. La chía además aumenta la saciedad.', '{"proteina":"8g","carbohidratos":"48g","grasas":"10g","fibra":"9g"}'::jsonb),

('jugo-verde-detox', 'Jugo verde detox', 'Un jugo fresco lleno de vitaminas para empezar el día limpia y ligera.', 5, 95, 1, 'facil', 'bebida', ARRAY['vegano','sin gluten','detox'], 'https://images.unsplash.com/photo-1622597467836-f3e6707e1191?auto=format&fit=crop&w=800&q=80', '[{"item":"Espinaca","cantidad":"1 taza"},{"item":"Pepino","cantidad":"1/2"},{"item":"Manzana verde","cantidad":"1"},{"item":"Limón","cantidad":"1/2"},{"item":"Jengibre","cantidad":"1 trocito"}]'::jsonb, '["Lava bien todos los ingredientes.","Procesa en juguera o licuadora con un poco de agua.","Cuela si lo prefieres más líquido y sirve frío."]'::jsonb, 'Tomarlo en ayunas ayuda a hidratar y a activar el sistema digestivo. Acompáñalo con una proteína después.', '{"proteina":"2g","carbohidratos":"22g","grasas":"0g","fibra":"5g"}'::jsonb),

('arepa-rellena-pollo', 'Arepa rellena de pollo y aguacate', 'La clásica arepa LATAM con un relleno saludable y saciante.', 20, 380, 1, 'medio', 'salado', ARRAY['alto en proteina','sin gluten'], 'https://images.unsplash.com/photo-1626078297018-0ec9adef9c6d?auto=format&fit=crop&w=800&q=80', '[{"item":"Harina de maíz precocida","cantidad":"1/2 taza"},{"item":"Agua tibia","cantidad":"1/3 taza"},{"item":"Pechuga de pollo cocida","cantidad":"80g"},{"item":"Aguacate","cantidad":"1/4"},{"item":"Sal","cantidad":"al gusto"}]'::jsonb, '["Mezcla la harina con agua y sal hasta formar masa suave.","Forma una arepa y cocínala en sartén 5 minutos por lado.","Ábrela por la mitad y rellena con pollo desmechado y aguacate."]'::jsonb, 'Combinar carbohidrato complejo con proteína magra y grasa buena es la fórmula perfecta del desayuno fit.', '{"proteina":"28g","carbohidratos":"40g","grasas":"12g","fibra":"5g"}'::jsonb),

('chia-pudding-vainilla', 'Chia pudding de vainilla', 'Cremoso, dulce y nutritivo. Perfecto para preparar la noche anterior.', 5, 220, 1, 'facil', 'dulce', ARRAY['vegano','sin gluten','meal prep','omega 3'], 'https://images.unsplash.com/photo-1542691457-cbe4df041eb2?auto=format&fit=crop&w=800&q=80', '[{"item":"Semillas de chía","cantidad":"3 cdas"},{"item":"Leche de almendras","cantidad":"1 taza"},{"item":"Esencia de vainilla","cantidad":"1/2 cdita"},{"item":"Endulzante natural","cantidad":"al gusto"},{"item":"Frutas frescas","cantidad":"para decorar"}]'::jsonb, '["Mezcla la chía con la leche, vainilla y endulzante.","Refrigera mínimo 4 horas o toda la noche.","Sirve con frutas frescas encima."]'::jsonb, 'Las semillas de chía aportan omega 3 vegetal, ideal para cuidar el corazón y la piel.', '{"proteina":"7g","carbohidratos":"18g","grasas":"12g","fibra":"11g"}'::jsonb),

('wrap-integral-pavo', 'Wrap integral de pavo y verduras', 'Un wrap rápido, ligero y lleno de proteína. Llévalo a la oficina.', 12, 340, 1, 'facil', 'salado', ARRAY['alto en proteina','para llevar'], 'https://images.unsplash.com/photo-1540713434306-58505cf1b6fc?auto=format&fit=crop&w=800&q=80', '[{"item":"Tortilla integral","cantidad":"1"},{"item":"Pavo en lonchas","cantidad":"60g"},{"item":"Hummus","cantidad":"2 cdas"},{"item":"Espinaca","cantidad":"1 puñado"},{"item":"Tomate","cantidad":"1/2"}]'::jsonb, '["Calienta la tortilla 20 segundos.","Unta el hummus.","Coloca el pavo, espinaca y tomate en el centro.","Enrolla apretado y corta por la mitad."]'::jsonb, 'El pavo es una de las proteínas más magras. Junto al hummus, te da energía sostenida toda la mañana.', '{"proteina":"24g","carbohidratos":"32g","grasas":"10g","fibra":"6g"}'::jsonb),

('bowl-yogur-granola', 'Bowl de yogur griego con granola casera', 'El clásico bowl proteico, fresco y crujiente.', 5, 270, 1, 'facil', 'dulce', ARRAY['alto en proteina','vegetariano'], 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80', '[{"item":"Yogur griego natural","cantidad":"1 taza"},{"item":"Granola sin azúcar","cantidad":"3 cdas"},{"item":"Fresas","cantidad":"5"},{"item":"Miel","cantidad":"1 cdita"},{"item":"Almendras","cantidad":"5 unidades"}]'::jsonb, '["Coloca el yogur en un bowl.","Agrega la granola por encima.","Decora con fresas en rodajas, miel y almendras picadas."]'::jsonb, 'El yogur griego tiene el doble de proteína que el yogur común. Ideal para músculos y saciedad.', '{"proteina":"20g","carbohidratos":"28g","grasas":"8g","fibra":"4g"}'::jsonb),

('tortilla-claras-champinones', 'Tortilla de claras con champiñones', 'Bajísima en grasa y altísima en proteína. Para días de entrenamiento.', 10, 180, 1, 'facil', 'salado', ARRAY['alto en proteina','bajo en grasa','keto'], 'https://images.unsplash.com/photo-1568625365131-079e026a927d?auto=format&fit=crop&w=800&q=80', '[{"item":"Claras de huevo","cantidad":"4"},{"item":"Champiñones","cantidad":"5"},{"item":"Cebolla","cantidad":"1/4"},{"item":"Aceite en spray","cantidad":"al gusto"},{"item":"Sal y pimienta","cantidad":"al gusto"}]'::jsonb, '["Saltea cebolla y champiñones picados con un poco de aceite.","Bate las claras con sal y pimienta.","Vierte sobre los vegetales y cocina a fuego bajo hasta cuajar.","Dobla por la mitad y sirve."]'::jsonb, 'Las claras de huevo son proteína pura sin grasa. Ideales si buscas perder peso sin perder masa muscular.', '{"proteina":"22g","carbohidratos":"6g","grasas":"3g","fibra":"2g"}'::jsonb),

('smoothie-proteico-cacao', 'Smoothie proteico de cacao y banana', 'Sabor a chocolate sin culpa. Listo en 3 minutos.', 5, 260, 1, 'facil', 'bebida', ARRAY['alto en proteina','vegetariano','post entreno'], 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80', '[{"item":"Banana congelada","cantidad":"1"},{"item":"Cacao en polvo","cantidad":"1 cda"},{"item":"Mantequilla de maní","cantidad":"1 cda"},{"item":"Leche de almendras","cantidad":"1 taza"},{"item":"Proteína en polvo","cantidad":"1 scoop (opcional)"}]'::jsonb, '["Coloca todo en la licuadora.","Procesa hasta obtener una mezcla cremosa.","Sirve frío en un vaso alto."]'::jsonb, 'El cacao puro tiene magnesio y antioxidantes. Perfecto antes o después del ejercicio.', '{"proteina":"18g","carbohidratos":"30g","grasas":"9g","fibra":"6g"}'::jsonb),

('frijoles-huevo-tortilla', 'Frijoles refritos con huevo y tortilla', 'Un desayuno LATAM completo, sustancioso y muy proteico.', 15, 410, 1, 'medio', 'salado', ARRAY['alto en proteina','sin gluten','tradicional'], 'https://images.unsplash.com/photo-1593503533537-c0e9b3b80c66?auto=format&fit=crop&w=800&q=80', '[{"item":"Frijoles negros cocidos","cantidad":"1/2 taza"},{"item":"Huevo","cantidad":"1"},{"item":"Tortilla de maíz","cantidad":"2"},{"item":"Aguacate","cantidad":"1/4"},{"item":"Salsa","cantidad":"al gusto"}]'::jsonb, '["Calienta los frijoles y aplástalos un poco.","Fríe el huevo en sartén con poco aceite.","Calienta las tortillas.","Sirve los frijoles, el huevo encima y aguacate al lado."]'::jsonb, 'Los frijoles son fuente vegetal de proteína y fibra. Junto al huevo logras un perfil de aminoácidos completo.', '{"proteina":"22g","carbohidratos":"48g","grasas":"14g","fibra":"12g"}'::jsonb),

('muffins-zanahoria-avena', 'Muffins de zanahoria y avena', 'Dulces, esponjosos y sin azúcar refinada. Hornea para toda la semana.', 35, 180, 6, 'medio', 'dulce', ARRAY['sin azucar','meal prep','vegetariano'], 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80', '[{"item":"Avena en hojuelas","cantidad":"1.5 tazas"},{"item":"Zanahoria rallada","cantidad":"1 taza"},{"item":"Huevos","cantidad":"2"},{"item":"Banana madura","cantidad":"1"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Polvo para hornear","cantidad":"1 cdita"}]'::jsonb, '["Precalienta el horno a 180°C.","Licúa la avena para hacer harina.","Mezcla todos los ingredientes en un bowl.","Distribuye en moldes para muffins y hornea 22 minutos."]'::jsonb, 'Hornea el domingo y ten desayuno listo toda la semana. Cada muffin tiene fibra y dura 5 días refrigerado.', '{"proteina":"6g","carbohidratos":"28g","grasas":"4g","fibra":"4g"}'::jsonb),

('avena-cocida-manzana', 'Avena cocida con manzana y canela', 'El desayuno reconfortante de toda la vida, en versión saludable.', 10, 290, 1, 'facil', 'dulce', ARRAY['vegano','sin azucar','reconfortante'], 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80', '[{"item":"Avena en hojuelas","cantidad":"1/2 taza"},{"item":"Leche de almendras","cantidad":"1 taza"},{"item":"Manzana","cantidad":"1"},{"item":"Canela","cantidad":"1 cdita"},{"item":"Nueces","cantidad":"5"}]'::jsonb, '["Pica la manzana en cubitos.","Cocina la avena con la leche y la canela 5 minutos a fuego bajo.","Agrega la manzana y cocina 2 minutos más.","Sirve con nueces picadas encima."]'::jsonb, 'La avena cocida en frío de la mañana resulta más digestiva. La canela ayuda a regular el azúcar en sangre.', '{"proteina":"8g","carbohidratos":"50g","grasas":"8g","fibra":"8g"}'::jsonb),

('cafe-proteico', 'Café proteico cremoso', 'Tu café de cada mañana, pero con un boost de proteína. Sin azúcar.', 5, 130, 1, 'facil', 'bebida', ARRAY['alto en proteina','sin azucar','keto'], 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80', '[{"item":"Café espresso","cantidad":"1 shot"},{"item":"Leche de almendras","cantidad":"3/4 taza"},{"item":"Proteína en polvo vainilla","cantidad":"1 scoop"},{"item":"Hielo","cantidad":"al gusto"},{"item":"Canela","cantidad":"una pizca"}]'::jsonb, '["Prepara el espresso y deja enfriar.","Licúa con la leche, proteína y hielo.","Sirve en vaso alto y espolvorea canela."]'::jsonb, 'Tomar proteína en la mañana ayuda a controlar el apetito durante todo el día. Perfecto para mujeres activas.', '{"proteina":"22g","carbohidratos":"6g","grasas":"3g","fibra":"1g"}'::jsonb),

('pan-pita-hummus', 'Pan pita con hummus y vegetales', 'Mediterráneo, fresco y con mucha fibra. Vegetariano completo.', 10, 320, 1, 'facil', 'salado', ARRAY['vegetariano','vegano','mediterraneo'], 'https://images.unsplash.com/photo-1571197119282-7c4e2c2fa6c5?auto=format&fit=crop&w=800&q=80', '[{"item":"Pan pita integral","cantidad":"1"},{"item":"Hummus","cantidad":"3 cdas"},{"item":"Pepino","cantidad":"1/2"},{"item":"Tomate cherry","cantidad":"5"},{"item":"Aceitunas","cantidad":"5"}]'::jsonb, '["Calienta el pan pita 30 segundos.","Ábrelo y unta hummus por dentro.","Rellena con pepino, tomate cherry y aceitunas picadas."]'::jsonb, 'El hummus aporta proteína vegetal y grasas buenas del aceite de oliva. Una opción mediterránea ideal.', '{"proteina":"12g","carbohidratos":"42g","grasas":"11g","fibra":"8g"}'::jsonb),

('quesadilla-verde-fit', 'Quesadilla verde fit con espinaca', 'Quesadilla saludable con tortilla integral, queso reducido y espinaca fresca.', 12, 310, 1, 'facil', 'salado', ARRAY['vegetariano','rapido'], 'https://images.unsplash.com/photo-1618040996337-17f6b6f25e4f?auto=format&fit=crop&w=800&q=80', '[{"item":"Tortilla integral","cantidad":"1"},{"item":"Queso mozzarella ligero","cantidad":"40g"},{"item":"Espinaca fresca","cantidad":"1 taza"},{"item":"Tomate","cantidad":"1/2"},{"item":"Salsa verde","cantidad":"al gusto"}]'::jsonb, '["Calienta la tortilla en sartén.","Pon el queso, espinaca y tomate en una mitad.","Dobla y cocina 2 minutos por lado hasta dorar.","Sirve con salsa verde al lado."]'::jsonb, 'Elegir tortilla integral en lugar de blanca duplica la fibra y prolonga la saciedad.', '{"proteina":"16g","carbohidratos":"32g","grasas":"12g","fibra":"6g"}'::jsonb),

('batido-fresa-avena', 'Batido de fresa y avena', 'Cremoso, dulce y muy saciante. Un desayuno completo en vaso.', 5, 280, 1, 'facil', 'bebida', ARRAY['vegetariano','rapido','para llevar'], 'https://images.unsplash.com/photo-1638176067000-9e02de50c7da?auto=format&fit=crop&w=800&q=80', '[{"item":"Fresas","cantidad":"1 taza"},{"item":"Avena en hojuelas","cantidad":"3 cdas"},{"item":"Leche descremada","cantidad":"1 taza"},{"item":"Yogur natural","cantidad":"1/2 taza"},{"item":"Miel","cantidad":"1 cdita"}]'::jsonb, '["Coloca todo en la licuadora.","Procesa 1 minuto hasta que quede cremoso.","Sirve frío y, si quieres, decora con fresa."]'::jsonb, 'La avena en el batido te da fibra que retrasa el vaciado gástrico. Te sentirás llena hasta el almuerzo.', '{"proteina":"14g","carbohidratos":"44g","grasas":"4g","fibra":"5g"}'::jsonb),

('huevos-rancheros-light', 'Huevos rancheros light', 'Versión liviana del clásico mexicano. Picante y delicioso.', 18, 360, 1, 'medio', 'salado', ARRAY['alto en proteina','tradicional','sin gluten'], 'https://images.unsplash.com/photo-1590005354167-6da97870c757?auto=format&fit=crop&w=800&q=80', '[{"item":"Tortilla de maíz","cantidad":"2"},{"item":"Huevos","cantidad":"2"},{"item":"Frijoles negros","cantidad":"1/3 taza"},{"item":"Salsa de tomate casera","cantidad":"1/4 taza"},{"item":"Cilantro fresco","cantidad":"al gusto"}]'::jsonb, '["Calienta las tortillas en sartén.","Fríe los huevos con poco aceite.","Calienta los frijoles y la salsa por separado.","Monta: tortilla, frijoles, huevo y baña con salsa. Decora con cilantro."]'::jsonb, 'Los huevos enteros aportan colina, esencial para la memoria y el funcionamiento cerebral en la mañana.', '{"proteina":"24g","carbohidratos":"38g","grasas":"14g","fibra":"9g"}'::jsonb)

ON CONFLICT (slug) DO NOTHING;